Sites = new Mongo.Collection('sites')
Hubs = new Mongo.Collection('hubs')
Firmwares = new Mongo.Collection('firmware')
Sensors1 = new Mongo.Collection('sensors1')
Things = new Mongo.Collection('things')
Readings = new Mongo.Collection('readings')
